### ISSUE TITLE
get_ilo_backup_files couldn't resolve module 'ilo_utils'

### ISSUE THREAD

**Issue by BrettMerrick** [HewlettPackard/ilo-ansible-collection#18]
Hi,

Just working with the 1.0.32 release and the get_ilo_backup_files role throws an error looking for the 'ilo_utils' module.

This is the repo linked from Ansible-Galaxy, however it seems to be different as I can't find the get_ilo_backup_files role here.

Am I looking in the correct place?

**Comment by BrettMerrick** [comment]
It also seems that many of the other roles fail with: "missing required fucntions in ilo_oem_utils.py"

**Comment by Bhavya06** [comment]
> o_utils

Hey @BrettMerrick  Could you mention the roles throwing error with : "missing required functions in ilo_oem_utils.py"?

**Comment by Bhavya06** [comment]
> Hi,
> 
> Just working with the 1.0.32 release and the get_ilo_backup_files role throws an error looking for the 'ilo_utils' module.
> 
> This is the repo linked from Ansible-Galaxy, however it seems to be different as I can't find the get_ilo_backup_files role here.
> 
> Am I looking in the correct place?



> It also seems that many of the other roles fail with: "missing required fucntions in ilo_oem_utils.py"



> It also seems that many of the other roles fail with: "missing required fucntions in ilo_oem_utils.py"

Hey @BrettMerrick Could you mention the roles throwing error with : "missing required functions in ilo_oem_utils.py"?

**Comment by Bhavya06** [comment]
> Hi,
> 
> Just working with the 1.0.32 release and the get_ilo_backup_files role throws an error looking for the 'ilo_utils' module.
> 
> This is the repo linked from Ansible-Galaxy, however it seems to be different as I can't find the get_ilo_backup_files role here.
> 
> Am I looking in the correct place?

We are looking into this

**Comment by rajeevkallur** [comment]
Did you do all the below setup?

Ansible set up
To install Ansible and Community general package use:

sudo python -m pip install ansible
ansible-galaxy collection install community.general
pip install python-ilorest-library

**Comment by donzef** [comment]
To be on the safe side, I would also issue a remove of the DMTF Redfish modules:

**pip uninstall redfish**
sudo python -m pip install ansible
ansible-galaxy collection install community.general
pip install python-ilorest-library

**Comment by Bhavya06** [comment]
Hi @BrettMerrick ,
We have made the appropriate changes and released a new build. Could you verify using the new files? Kindly notice the changes done to the readme as well. We have added 2 new modules to install.

**Comment by Bhavya06** [comment]
Hi @BrettMerrick ,
We have made the appropriate changes and released a new build on Ansible galaxy. Could you verify using the new files? Kindly notice the changes done to the readme as well. We have added 2 new modules to install.

**Comment by rajeevkallur** [comment]
Fixed
