### ISSUE TITLE
Question: valid Commands for redfish_command

### ISSUE THREAD

**Issue by stephan-koch** [HewlettPackard/ilo-ansible-collection#2]
Is there any documentation available for the valid categories and commands for the redfish_command module ?
As an axample:
 redfish_command:
    category: Accounts
    command: UpdateUserName
...here the category and the command UpdateUserName ...

**Comment by donzef** [comment]
The redfish_info, redfish_command and redfish_config have been created and are maintained by the DMTF. See first:

* redfish_command [doc](https://docs.ansible.com/ansible/latest/collections/community/general/redfish_command_module.html)
* redfish_info [doc](https://docs.ansible.com/ansible/latest/collections/community/general/redfish_info_module.html) 
* redfish_config [doc](https://docs.ansible.com/ansible/latest/collections/community/general/redfish_config_module.html)

Then, to get the exhaustive list of categories and commands, you need look at the CATEGORY_COMMANDS_ALL python object in the sources. You will find all commands for all categories.

* [redfish_command.py](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/remote_management/redfish/redfish_command.py)
* [redfish_info.py](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/remote_management/redfish/redfish_info.py)
* [redfish_config](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/remote_management/redfish/redfish_config.py)

If you find a better way, I'll take it.

**Comment by atkinsroy** [comment]
Still no decent documentation. I'm wondering how actively funded/supported this collection is.

**Comment by Bhavya06** [comment]
Hi @stephan-koch and @atkinsroy 
The documentation links provided by @donzef is the documentation handled by redfish. It is an automated documentation that is generated by the module creation. Could you let us know what information you are looking so I could help you?

**Comment by rajeevkallur** [comment]
Please open a new case if you are looking for specific info on any specific module.  We will look into it.
