### ISSUE TITLE
GetLogicalDrives and GetPhysicalDrives yield no results

### ISSUE THREAD

**Issue by MaroWielki** [HewlettPackard/ilo-ansible-collection#25]
Hello,
We are unable to list Physical / Logical drives when running the 1.0.30 version of ilo-ansible-collection against HP server (ilo v5) 

Both Physical and Logical drives are visible when accesed via web GUI with the same user ansible is running with.

ok: [localhost] => {
    "changed": false,
    "ilo_storage": {
        "GetLogicalDrives": {
            "msg": {
                "logical_drives_details": []
            },
            "ret": true
        },
        "ret": true
    },
    "invocation": {
        "module_args": {
            "auth_token": null,
            "baseuri": "X.X.X.X",
            "category": [
                "Systems"
            ],
            "cert_file": null,
            "command": [
                "GetLogicalDrives"
            ],
            "key_file": null,
            "logical_drives_names": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "raid_details": null,
            "timeout": 60,
            "username": "user"
        }
    }
}

ok: [localhost] => {
    "changed": false,
    "ilo_storage": {
        "GetPhysicalDrives": {
            "msg": {
                "physical_drives": {},
                "physical_drives_count": 0
            },
            "ret": true
        },
        "ret": true
    },
    "invocation": {
        "module_args": {
            "auth_token": null,
            "baseuri": "X.X.X.X",
            "category": [
                "Systems"
            ],
            "cert_file": null,
            "command": [
                "GetPhysicalDrives"
            ],
            "key_file": null,
            "logical_drives_names": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "raid_details": null,
            "timeout": 60,
            "username": "user"
        }
    }
}

Can you please advise what could be causing the problem?

**Comment by TSKushal** [comment]
Hi, could you provide more details, like the Sever model, Storage Controller and physical drive details.

**Comment by MaroWielki** [comment]
Product Name: ProLiant DL380 Gen10 Plus
iLO Firmware Version
: 2.98 Oct 10 2023

Controller: HPE MR416i-a Gen10+      firmware: 52.24.3-4948
physical drive model: VK000960GZXQU

**Comment by TSKushal** [comment]
These modules are only applicable for smart storage controllers.

**Comment by rajeevkallur** [comment]
No update from Submitter. Closing it.
