### ISSUE TITLE
redfish_info module does not support auth_token parameter

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/ilo-ansible-collection#5]
In get_system_inventory_all.yml, when using auth_token, we get an error message:
 "Unsupported parameters for (redfish_info) module: auth_token Supported parameters include: baseuri, category, command, password, timeout, username"}

**Comment by rajeevkallur** [comment]
Please use the latest playbooks and latest community.general release.  Auth_token has been added in that.
