### ISSUE TITLE
problem to update ilo pass

### ISSUE THREAD

**Issue by ckirim1** [HewlettPackard/ilo-ansible-collection#6]
when I play the role " updatepass", I receive "Bad Request" error. 
I already operated "updaterole" without any issue. But update request to ILO password is not successful.

-----------

---
# tasks file for updatepass
- name: Update user password
  redfish_command:
    category: Accounts
    command: UpdateUserPassword
    baseuri: "172.16.16.12"
    username: "ckirim"
    password: "admin123"
    account_username: "ckirim"
    account_password: "serkan"
~
 ----------------------------

(oneview) [root@localhost ilo]# ansible-playbook playbook.yml -vvv
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.6.12 (default, Sep 15 2020, 12:49:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-37)]. This feature will be removed
 from ansible-core in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ansible-playbook [core 2.11.7]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/oneview/lib64/python3.6/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /root/oneview/bin/ansible-playbook
  python version = 3.6.12 (default, Sep 15 2020, 12:49:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-37)]
  jinja version = 3.0.3
  libyaml = True
No config file found; using defaults
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
ini declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
toml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
[WARNING]: running playbook inside collection hpe.ilo
redirecting (type: modules) ansible.builtin.redfish_command to community.general.redfish_command
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: playbook.yml **********************************************************************************************************************************************************************************************************************
1 plays in playbook.yml

PLAY [localhost] ****************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
task path: /root/.ansible/collections/ansible_collections/hpe/ilo/playbook.yml:2
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1645442563.2000966-129058-278645987446545 `" && echo ansible-tmp-1645442563.2000966-129058-278645987446545="` echo /root/.ansible/tmp/ansible-tmp-1645442563.2000966-129058-278645987446545 `" ) && sleep 0'
Using module file /root/oneview/lib64/python3.6/site-packages/ansible/modules/setup.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-129051_vkfwboz/tmpt41t_lb7 TO /root/.ansible/tmp/ansible-tmp-1645442563.2000966-129058-278645987446545/AnsiballZ_setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1645442563.2000966-129058-278645987446545/ /root/.ansible/tmp/ansible-tmp-1645442563.2000966-129058-278645987446545/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/root/oneview/bin/python3.6 /root/.ansible/tmp/ansible-tmp-1645442563.2000966-129058-278645987446545/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1645442563.2000966-129058-278645987446545/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [hpe.ilo.updatepass : Update user password] ********************************************************************************************************************************************************************************************
task path: /root/.ansible/collections/ansible_collections/hpe/ilo/roles/updatepass/tasks/main.yml:3
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1645442564.411589-129120-34397279681846 `" && echo ansible-tmp-1645442564.411589-129120-34397279681846="` echo /root/.ansible/tmp/ansible-tmp-1645442564.411589-129120-34397279681846 `" ) && sleep 0'
redirecting (type: modules) ansible.builtin.redfish_command to community.general.redfish_command
Using module file /root/.ansible/collections/ansible_collections/community/general/plugins/modules/redfish_command.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-129051_vkfwboz/tmpg7x1c33g TO /root/.ansible/tmp/ansible-tmp-1645442564.411589-129120-34397279681846/AnsiballZ_redfish_command.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1645442564.411589-129120-34397279681846/ /root/.ansible/tmp/ansible-tmp-1645442564.411589-129120-34397279681846/AnsiballZ_redfish_command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/root/oneview/bin/python3.6 /root/.ansible/tmp/ansible-tmp-1645442564.411589-129120-34397279681846/AnsiballZ_redfish_command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1645442564.411589-129120-34397279681846/ > /dev/null 2>&1 && sleep 0'
[WARNING]: Module did not set no_log for account_password
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "account_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "account_properties": {},
            "account_username": "ckirim",
            "auth_token": null,
            "baseuri": "172.16.16.12",
            "boot_next": null,
            "boot_override_mode": null,
            "bootdevice": null,
            "category": "Accounts",
            "command": [
                "UpdateUserPassword"
            ],
            "id": null,
            "new_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "new_username": "ckirim",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "resource_id": null,
            "roleid": null,
            "session_uri": null,
            "strip_etag_quotes": false,
            "timeout": 10,
            "uefi_target": null,
            "update_creds": null,
            "update_image_uri": null,
            "update_protocol": null,
            "update_targets": [],
            "update_username": null,
            "username": "ckirim",
            "virtual_media": null
        }
    },
    "msg": "HTTP Error 400 on PATCH request to 'https://172.16.16.12/redfish/v1/AccountService/Accounts/3', extended message: 'Bad Request'"
}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

---------------------------------------------

**Comment by rajeevkallur** [comment]
I asked my internal team to check.

**Comment by rajeevkallur** [comment]
![image](https://user-images.githubusercontent.com/21117913/155265031-067fa1d1-f7a6-4b3c-a009-dc82000ccc18.png)

**Comment by rajeevkallur** [comment]
It is working for us. Please check the password length and other password requirements

**Comment by ckirim1** [comment]
thanks for the reply. Its working when I give 8 characters password.  :)

**Comment by rajeevkallur** [comment]
Great...Closing it
