### ISSUE TITLE
Setonetime boot calls  handler for reboot that fails

### ISSUE THREAD

**Issue by kristyburns** [HewlettPackard/ilo-ansible-collection#7]
Setonetimeboot role sends message to "Reboot system to apply new BIOS settings" but then has a handler that makes does a reboot using redfish_command powerReboot that fails with ILO 5.  Why is this handler being called if the role is suggesting in return message to reboot.  And why do we need to reboot?  That is not necessary to set the onetime boot.

**Comment by rajeevkallur** [comment]
We have updated our collection to fix this
